src/Areas/Identity/Pages/Users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;
using RazorPagesMovie.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;

namespace RazorPagesMovie.Areas.Identity.Pages.Users
{
    [Authorize(Roles=IdentityData.AdminRoleName)] // Solo los usuarios con rol administrador pueden acceder a este controlador
    public class DeleteModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public DeleteModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.Users.FindAsync(id);

            if (ApplicationUser != null)
            {
                _context.Users.Remove(ApplicationUser);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/Areas/Identity/Pages/Users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;
using RazorPagesMovie.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;

namespace RazorPagesMovie.Areas.Identity.Pages.Users
{
    [Authorize(Roles=IdentityData.AdminRoleName)] // Solo los usuarios con rol administrador pueden acceder a este controlador
    public class DetailsModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public DetailsModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/Areas/Identity/Pages/Users/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace RazorPagesMovie.Areas.Identity.Pages.Users
{
    [Authorize(Roles=IdentityData.AdminRoleName)] // Solo los usuarios con rol administrador pueden acceder a este controlador
    public class EditModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public EditModel(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

            this.RolesList = new List<SelectListItem>();
            for (int i = 0; i < IdentityData.NonAdminRoleNames.Length; i++)
            {
                this.RolesList.Add(new SelectListItem { Value = i.ToString(), Text = IdentityData.NonAdminRoleNames[i] });
            }
        }

        [BindProperty]
        public ApplicationUser ApplicationUser { get; set; }

        [BindProperty]
        public int Role { get; set; }

        [BindProperty]
        public List<SelectListItem> RolesList { get; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _userManager.FindByIdAsync(id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }

            this.Role = Array.BinarySearch(IdentityData.NonAdminRoleNames, ApplicationUser.Role);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByIdAsync(this.ApplicationUser.Id);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var rolesForUser = await _userManager.GetRolesAsync(user);
            foreach (var roleToRemove in rolesForUser)
            {
                if (roleToRemove.Equals(IdentityData.AdminRoleName))
                {
                    throw new InvalidOperationException($"Cannot edit '{IdentityData.AdminRoleName}'.");
                }
                _userManager.RemoveFromRoleAsync(user, roleToRemove).Wait();
            }

            var roleToAdd = await _roleManager.FindByNameAsync(IdentityData.NonAdminRoleNames[this.Role]);
            _userManager.AddToRoleAsync(user, roleToAdd.Name).Wait();

            // Es necesario tener acceso a RoleManager para poder buscar el rol de este usuario; se asigna aquí para poder
            // buscar por rol después cuando no hay acceso a RoleManager.
            user.AssignRole(_userManager, roleToAdd.Name);

            await _userManager.UpdateAsync(user);

            return RedirectToPage("./Index");
        }

        private bool ApplicationUserExists(string id)
        {
            var user = _userManager.FindByIdAsync(id);
            return user != null;
        }
    }
}

src/Pages/Actors/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages_Actors
{
    public class CreateModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public CreateModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Actor Actor { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _context.AddActorAsync(Actor);

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Actors/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages_Actors
{
    public class DeleteModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public DeleteModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Actor Actor { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Actor = await _context.GetActorByIdAsync(id);
            if (Actor == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Actor = await _context.GetActorByIdAsync(id);

            if (Actor != null)
            {
                await _context.RemoveActorAsync(Actor);
            }

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Actors/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages_Actors
{
    public class DetailsModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public DetailsModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        public Actor Actor { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Actor = await _context.GetActorByIdAsync(id);

            if (Actor == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/Pages/Locations/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages.Locations
{
    public class CreateModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public CreateModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["MovieID"] = new SelectList(_context.Movies, "ID", "Genre");
            return Page();
        }

        [BindProperty]
        public Location Location { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Location.Add(Location);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/Pages/Movies/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Pages.Movies
{
    public class EditModel : PageModel
    {
        private readonly RazorPagesMovie.Models.ApplicationContext _context;

        public EditModel(RazorPagesMovie.Models.ApplicationContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Movie Movie { get; set; }

        public IEnumerable<Actor> Actors { get; set; }

        public IEnumerable<Actor> AllActors { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Retrieve the first movie with ID equal to received id. Include the appeareances of actors in that
            // movie. Then include the actors in the appearences of the movie.
            Movie = await _context.Movies
                .Where(m => m.ID == id)
                .Include(l => l.Location)
                .Include(c => c.Appeareances)
                    .ThenInclude(a => a.Actor)
                .AsNoTracking()
                .FirstOrDefaultAsync();

            if (Movie == null)
            {
                return NotFound();
            }

            // Populate the list of actors in the viewmodel with the actors of the movie.
            this.Actors = Movie.Appeareances
                .Select(a => a.Actor);

            string nameFilter = "";
            if (this.SearchString != null)
            {
                nameFilter = this.SearchString.ToUpper();
            }

            // Populate the list of all other actors with all actors not included in the movie's actors and
            // included in the search filter.
            this.AllActors = await _context.Actors
                .Where(a =>!Actors.Contains(a))
                .Where(a => !string.IsNullOrEmpty(nameFilter) ? a.Name.ToUpper().Contains(nameFilter) : true)
                .ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var movieToUpdate = await _context.Movies
                .Include(l => l.Location)
                .Include(a => a.Appeareances)
                    .ThenInclude(a => a.Actor)
                .FirstOrDefaultAsync(m => m.ID == id);


            if (await TryUpdateModelAsync<Movie>(
                movieToUpdate,
                "Movie",
                i => i.Title, i => i.ReleaseDate,
                i => i.Price, i => i.Genre,
                i => i.Location))
            {
                if (String.IsNullOrWhiteSpace(movieToUpdate.Location?.Name))
                {
                    movieToUpdate.Location = null;
                }

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(Movie.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteActorAsync(int id, int actorToDeleteID)
        {
            Movie movieToUpdate = await _context.Movies
                .Include(l => l.Location)
                .Include(a => a.Appeareances)
                    .ThenInclude(a => a.Actor)
                .FirstOrDefaultAsync(m => m.ID == id);

            await TryUpdateModelAsync<Movie>(movieToUpdate);

            var actorToDelete = movieToUpdate.Appeareances.Where(a => a.ActorID == actorToDeleteID).FirstOrDefault();
            if (actorToDelete != null)
            {
                movieToUpdate.Appeareances.Remove(actorToDelete);
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(Movie.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Redirect(Request.Path + $"?id={id}");
        }

        public async Task<IActionResult> OnPostAddActorAsync(int? id, int? actorToAddID)
        {
            Movie movieToUpdate = await _context.Movies
                .Include(a => a.Appeareances)
                    .ThenInclude(a => a.Actor)
                .FirstOrDefaultAsync(m => m.ID == Movie.ID);

            await TryUpdateModelAsync<Movie>(movieToUpdate);


            if (actorToAddID != null)
            {
                Actor actorToAdd = await _context.Actors.Where(a => a.ID == actorToAddID).FirstOrDefaultAsync();
                if (actorToAdd != null)
                {
                    var appereanceToAdd = new Appereance() {
                        ActorID = actorToAddID.Value,
                        Actor = actorToAdd,
                        MovieID = movieToUpdate.ID,
                        Movie = movieToUpdate };
                    movieToUpdate.Appeareances.Add(appereanceToAdd);
                }
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(Movie.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Redirect(Request.Path + $"?id={id}");
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.ID == id);
        }
    }
}

src/Pages/Movies/Create.cshtml
@page
@model RazorPagesMovie.Pages.Movies.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                <input asp-for="Movie.ReleaseDate" class="form-control" />
                <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Genre" class="control-label"></label>
                <input asp-for="Movie.Genre" class="form-control" />
                <span asp-validation-for="Movie.Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Price" class="control-label"></label>
                <input asp-for="Movie.Price" class="form-control" />
                <span asp-validation-for="Movie.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Rating" class="control-label"></label>
                <input asp-for="Movie.Rating" class="form-control" />
                <span asp-validation-for="Movie.Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Location.Name" class="control-label"></label>
                <input asp-for="Movie.Location.Name" class="form-control" />
                <span asp-validation-for="Movie.Location.Name" class="text-danger" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Pages/Movies/Delete.cshtml
@page
@model RazorPagesMovie.Pages.Movies.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Rating)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Movie.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

src/Pages/Movies/Details.cshtml
@page "{id:int?}"
@model RazorPagesMovie.Pages.Movies.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Movie.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

src/Pages/Movies/Edit.cshtml
@page "{id:int?}"
@model RazorPagesMovie.Pages.Movies.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<form method="post">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Movie.ID" />
            <div class="form-group">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control" />
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                <input asp-for="Movie.ReleaseDate" class="form-control" />
                <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Genre" class="control-label"></label>
                <input asp-for="Movie.Genre" class="form-control" />
                <span asp-validation-for="Movie.Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Price" class="control-label"></label>
                <input asp-for="Movie.Price" class="form-control" />
                <span asp-validation-for="Movie.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Rating" class="control-label"></label>
                <input asp-for="Movie.Rating" class="form-control" />
                <span asp-validation-for="Movie.Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie.Location.Name" class="control-label"></label>
                <input asp-for="Movie.Location.Name" class="form-control" />
                <span asp-validation-for="Movie.Location.Name" class="text-danger" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-8">
        @if (Model.Actors != null)
        {
            <h4>Cast</h4>
            <table class="table">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Birth Data</th>
                    <th>Awards</th>
                </tr>

                @foreach (var item in Model.Actors)
                {
                    string actorToDeleteID = item.ID.ToString();
                    <tr>
                        <td>
                            <form method="post" asp-page-handler="DeleteActor"
                                asp-route-id="@Model.Movie.ID" asp-route-actorToDeleteID="@actorToDeleteID">
                                <button class="btn btn-default">Delete</button>
                            </form>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BirthDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AwardedBestActor)
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
</div>

<div class="row">
    <div class="col-md-8">

        @if (Model.AllActors != null)
        {
            <h4>Other Actors</h4>
            <form>
                <p>
                    Name: <input type="text" asp-for="SearchString" />
                    <input type="submit" value="Filter" />
                </p>
            </form>
            <table class="table">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Birth Data</th>
                    <th>Awards</th>
                </tr>

                @foreach (var item in Model.AllActors)
                {
                    string actorToAddID = item.ID.ToString();
                    <tr>
                        <td>
                            <form method="post" asp-page-handler="AddActor"
                                asp-route-id="@Model.Movie.ID" asp-route-actorToAddID="@actorToAddID">
                                <button class="btn btn-default">Add</button>
                            </form>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BirthDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AwardedBestActor)
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Pages/Movies/Index.cshtml
@page "{id:int?}"
@model RazorPagesMovie.Pages.Movies.IndexModel
@using RazorPagesMovie.Models;

@{
    ViewData["Title"] = "Movies";
}

<h1>Movies</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<form>
    <p>
        <select asp-for="MovieGenre" asp-items="Model.Genres">
            <option value="">All</option>
        </select>
        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Release Date</th>
            <th>Genre</th>
            <th>Price</th>
            <th>Rating</th>
            <th>Location</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Movie.Movies)
        {
            string selectedRow = "";
            if (item.ID == Model.MovieID)
            {
                selectedRow = "table-success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @if (item.Location != null)
                    {
                        @item.Location.Name
                    }
                </td>
                <td>
                    <a asp-page="./Index" asp-route-id="@item.ID">Select</a> |
                    <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.Movie.Actors != null)
{
    <h3>Cast in Selected Movie</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Name</th>
            <th>Birth Data</th>
            <th>Awards</th>
        </tr>

        @foreach (var item in Model.Movie.Actors)
        {
            string selectedRow = "";
            if (item.ID == Model.ActorID)
            {
                selectedRow = "table-success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.ActionLink("Select", "OnGetAsync",
                                  new { actorID = item.ID })
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.BirthDate
                </td>
                <td>
                    @item.AwardedBestActor
                </td>
            </tr>
        }
    </table>
}